package NVMP.AppService.Interface;
import java.io.IOException;
import java.util.List;
import corenet.netbase.Interface.*;
import corenet.rpc.*;



///////////////////////////////////////////////////////////
//  IAppRuntime.cs
//  Implementation of the Interface IAppRuntime
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:46
//  Original author: Administrator
///////////////////////////////////////////////////////////

 


//using System.Windows.Forms;


/** 
 ÓŠÓÃ·þÎñÆ÷ÔËÐÐÊ±œÓ¿Ú,ÔÚ×éŒþ±»ŒÓÔØµ÷ÓÃÆäÈë¿Ú ComEntry Ê±Ž«Èë¡£
 
*/
public interface IAppRuntime
{

	/** 
	 µÃµœµ±Ç°µÄ»á»°ÍšÐÅÐÅµÀ£¬ÔÚÒµÎñ×éŒþÖÐµ÷ÓÃžÃ·œ·š
	 
	*/
	String GetCurChannel();
	
	/**
	 * 说明：
	 * 1、Session://  对个人，如果本中心无，就广播
	 * 2、Group:// 对组，一定广播
	 * 3、ALL  所有人
	 * 4、Local:// 只对本中心。
	 * 
	 * */
	void SetCurChannel(String ChannelIds);
    String getSource();
    String getTarget();
    
	/** 
	 Íš¹ýÃû³Æ²éÕÒÒ»žö¶ÔÏó£º
	 1.²éÕÒµÄ¶ÔÏó³ý×¢²áµÄÒµÎñ¶ÔÏó
	 2.ÏµÍ³ÃüÃû¿ÕŒäÏÂµÄ¶ÔÏó¡£
	 
	 @param Name
	*/
	Object LookupObject(String Name);

	/** 
	 ÏòÓŠÓÃ·þÎñÆ÷×¢²áÒ»žöÒµÎñ¶ÔÏó
	 
	 @param o
	 <bool name="Name">
	*/
	boolean RegisterObject(String DomainName, Object o, String Name);

	IChannel CreateLocalChannel(String Sessionid,String IP,int port) throws IOException;
	public void LocalChannelSendMessage(IMessage message,String target,String source,String nosend);

	void EventHandler(java.util.HashMap<String, Object> Params,
			Object Context);
	
    /**
     * ÕÒµœŽúÀíÀàÓÃµÄ
     * **/
	
	Object LookupProxy(String name);
	public IMessage Dispatch(IMessage Message);
	
	
	
	/**
	 * ŽŽœš ÍšÐÅ×é
	 * @param groupName ×éÃû 
	 * */
	public boolean CreateGroup(String groupName);
	public void jionGroup(String userId, String group);
	
	/**
	 * »ñÈ¡Ä¿Ç°ËùÓÐ×éÃû
	 * 
	 * */
	public List<String> ShowGroupList();
	void setContinueFlag(boolean b);
	String getServerId();
	String getIP(String sessionid);
	
	boolean isActiveSession(String client);
	
	String getLev();
	void setLev(String lev);
//	int getLimitNum();

	void LocalUpSendMessage(IMessage message, String target, String source);

	void LocalDownSendMessage(IMessage message, String target, String source);

	
} //end IAppRuntime
 //end namespace ÓŠÓÃ·þÎñÆ÷
