package corenet.rpc;

///////////////////////////////////////////////////////////
//  IMessage.cs
//  Implementation of the Interface IMessage
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:51
//  Original author: Administrator
///////////////////////////////////////////////////////////


//using System.Windows.Forms;



	/**  
	 ¶ÔÏó»¯µÃÏûÏ¢¶ÔÏó
	 
	*/
	public interface IMessage
	{

		/** 
		 @param Name
		*/
		Object GetParam(String Name);
		void AddParam(String Name, Object o);

		/** 
		 »ñÈ¡ÏûÏ¢ÔŽµØÖ·
		 
		*/
		String MessageSrc();

		void SetObjURL(String ObjURL);
		String GetObjURL();
		String Serilize();

		String GetAction();
		void SetAction(String Action);

	} //end IMessage
 //end namespace ÓŠÓÃ·þÎñÆ÷
