package NVMP.AppService.Interface;

import java.util.List;

import corenet.rpc.IMessage;

///////////////////////////////////////////////////////////
//  IBusinessCom.cs
//  Implementation of the Interface IBusinessCom
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:45
//  Original author: Administrator
///////////////////////////////////////////////////////////
 


//using System.Windows.Forms;




/** 
 ÒµÎñ×éŒþœÓ¿Ú¶šÒå
 
 
*/
public interface IBusinessDomain
{



	boolean DomainEntry(IAppRuntime AppRuntime);
	
	
	/**
	 * ÍšÖªÒµÎñ¹ØÓÚÍšµÀÏà¹ØÏûÏ¢
	 * 
	 * */
	
	public  void OnDomainMessage(String Sessionid,String Groupid,String state,String type);
	

	/** 
	 ÒµÎñ×éŒþ±»Ð¶ÔØÊ±µ÷ÓÃ
	 
	*/
	void DomainUnload();

	String GetDescription();

	/** 
	 »ñÈ¡ÓŠÓÃÓòÃû³Æ£¬žÃ×éŒþ×¢²áµÄ¶ÔÏó¶ŒÔÚžÄÃüÃû¿ÕŒäÏÂ
	 
	*/
	 String GetDomainName();
	 
	 
	 //用来获得该业务需要与其它各个中心进行同步的信息
	 List<IMessage> getCenterMessage();
	 
	 
	 
} //end IBusinessCom
 //end namespace ÓŠÓÃ·þÎñÆ÷
