package NVMP.AppService.Interface;

///////////////////////////////////////////////////////////
//  IComLoader.cs
//  Implementation of the Interface IComLoader
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:43
//  Original author: Administrator
///////////////////////////////////////////////////////////


//using System.Windows.Forms;

/** 
 * 组件加载接口定义
 *
 */

import java.util.ArrayList;

public interface IComLoader
{
	/** 
	 * 根据组件路径，和url返回一个Domain对象
	 *
	 * ComPath 组件路径
	 * url     Domain URL，这里的URL等同于Domain 的名称，在开始的设计中Domain是可以嵌套的
	 *         如在 Domain A 下有Domain b。因为没有使用嵌套， 此时url 等同于Domain的名称
	 *
	 */
	IBusinessDomain LoadBusinessComponent(String ComPath,String url);

	/**
     *  
	 * 根据组件路径，返回该组件中的所有Domain对象集合
	 * 
	 * ComPath 组件路径
	 *
	 */
	ArrayList<IBusinessDomain> LoadBusinessComponent(String ComPath);
}




