package NVMP.AppService.Interface;
import corenet.rpc.*;

///////////////////////////////////////////////////////////
//  IBusinessObject.cs
//  Implementation of the Interface IBusinessObject
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:47
//  Original author: Administrator
///////////////////////////////////////////////////////////
 



//using NVMP.AppService.Implement;




/** 
 ÓŠÓÃ·þÎñÆ÷¶ËÒµÎñ¶ÔÏó£¬ÒµÎñ×éŒþÏòÔËÐÐÊ±×¢²áÒµÎñ¶ÔÏóÊ±£¬¶ÔÓŠ»áŽŽœšÒ»žö·þÎñ¶ËÒµÎñ¶ÔÏó¡£
 
*/
public interface IBusinessObject
{

	void AddMethod(String aName, NVMPMethodInfo aMethodInfo);

	/** 
	 ŽÓÏûÏ¢ÖÐ»ñÈ¡²ÎÊý£¬µ÷ÓÃÊµŒÊÒµÎñ¶ÔÏóµÄÊµÏÖ¡£
	 ²¢°Ñ¶ÔÏóµÄ·µ»Ø²ÎÊýŽò°ü³ÉÏûÏ¢žøÓŠÓÃ·þÎñÔËÐÐÊ±¡£
	 Ä¬ÈÏµ±Ç°»á»°¶ÔÏó¡£
	 
	 @param MethodName
	 @param Message
	*/
	 IMessage CallMethod(String MethodName, IMessage Message);

} //end IBusinessObject
 //end namespace ÓŠÓÃ·þÎñÆ÷
