package NVMP.AppService.Implement;

import java.net.URL;
import java.net.URLClassLoader;

import javassist.ClassPool;

import NVMP.AppService.Interface.*;
import java.util.ArrayList;
///////////////////////////////////////////////////////////
//  ManagedLoader.cs
//  Implementation of the Class ManagedLoader
//  Generated by Enterprise Architect
//  Created on:      30-ÎåÔÂ-2011 16:34:50
//  Original author: Administrator
///////////////////////////////////////////////////////////

 



public class ManagedLoader implements IComLoader
{

	public ManagedLoader()
	{

	}

	protected void finalize() throws Throwable
	{

	}

	/**
	 * by zzw
	 * 
	 * ÅÐ¶ÏÊÇÀàÊÇ·ñÊµÏÖžÃœÓ¿Ú
	 * */
	
	public boolean isInterface(Class<?> a,String name) {
		boolean b = false;
		for(Class<?> c : a.getInterfaces()) {
			if (c.getSimpleName().equals(name)) {
				b = true;
				break;			
			}
		}	
		return b;
		
	}

	// stub
	public final ArrayList<IBusinessDomain> LoadBusinessComponent(String ComPath)
	{
		return null;
	}
	
	
	
	public final IBusinessDomain LoadBusinessComponent(String ComPath,String str)
	{
		
        /**
         * by zzw
         * 
         * ±Ÿ¶ÎŽúÂëÊÇžùŸÝÀàÃû£¬×Ô¶¯Éú³ÉÀà¶ÔÏó£¬È»ºóÊµÁÐ»¯¡£
         * 
         */
		Object obj = null;
		try {
			Class<?> a;
			//ÕâÀïÐèÒªµ÷ÓÃurlLoaderœøÐÐÍâ²¿ŒÓÔØ¡£
			if(str!=null && !str.equals("")) {
			 URL url = new URL("file:"+str);
			 ClassPool.getDefault().appendClassPath(str);
			 
			 URLClassLoader myClassLoader  =   new  URLClassLoader( new  URL[]   { url } );
			  a  =  myClassLoader.loadClass(ComPath);
			} else {							
				a = Class.forName(ComPath);
			}
			//Class<?> a = Class.forName(ComPath);
			
			String name = "IBusinessDomain";
			if(isInterface(a,name)) {
				obj = a.newInstance();	
			}

			return (IBusinessDomain)obj;

		} catch(Exception e) {
			e.printStackTrace();
		}
		return null;
		
		
		/**
		 * by zzw
		 * ÏÂÃæÍ³Í³ÆÁ±Î 
		 * 
		 * */
		/*
		// 1. Íš¹ý·ŽÉäŒÓÔØÀà¿â
		System.Reflection.Assembly ass;
		Object obj=null;

		try
		{
			ass = Assembly.LoadFrom(ComPath);

			// 2. ±éÀúÀàÐÍÊµÏÖIBusinessDomain ÀàÐÍ
			for (java.lang.Class type : ass.GetTypes())
			{
				String Name = "IBusinessDomain";

				for (java.lang.Class myType : type.GetInterfaces())
				{
					if (myType.IsInterface && Name.equals(myType.getName()))
					{
						obj = ass.CreateInstance(type.FullName);
						break;
					}

				}
				if (obj != null)
				{
					break;
				}

			}
		}
		finally
		{

		}

		// 3. ÊµÀý»¯BusinessDomain¶ÔÏó£¬²¢·µ»Ø

		return obj;
		*/
	}

	public void dispose()
	{

	}


} //end ManagedLoader
 //end namespace ÓŠÓÃ·þÎñÆ÷
